### ISSUE TITLE
 fluentd/imagescripts/docker-entrypoint.sh never executed

### ISSUE THREAD

**Issue by theazz** [blacklabelops/fluentd#1]
I think here 
`if [ -n "${TAIL_LOG_FILE_PATTERN}" ] || [ -n "${TAIL_LOG_FILE_ENDINGS}" ] || [ -n "${TAIL_LOG_FILE_ENDINGS}" ]; then`
should be TAIL_LOGS_DIRECTORIES instead of  last TAIL_LOG_FILE_ENDINGS

**Comment by blacklabelops** [comment]
I will just add it.
